### ISSUE TITLE
Omissions, errors and typos

### ISSUE THREAD

**Issue by johnboc** [creativetimofficial/ct-material-dashboard-pro-laravel#4] opened 2019-09-09 11:09 UTC
In your documentation under Build Tools you say: "You can set in gulpfile.js from your downloaded archive any page you want to open in browser, at line 30: gulp.src('examples/dashboard.html')." But in the material-dashboard-pro-laravel-v1.0.0.zip there is not a gulpfile.js in the project folder.

There is an undefined variable: classPage in View: resources\views\layouts\page_templates\guest.blade.php and I cannot see how to fix this.

In resources\views\profile\edit.blade.php line 63 and 107 have a typo. It should be {{ __('Update Profile') }} and {{ __('Change password') }} and not {{ _('Update Profile') }} or {{ _('Change password') }}

**Comment by eugentudorache** [comment] 2019-09-10 08:01
Hello @johnboc, the Build Tools docs page is only related to the frontend assets of the theme.

We'll check the issue and follow up soon, thank you!

Eugen

**Comment by eugentudorache** [comment] 2019-09-10 14:06
Hello @johnboc 
We cannot reproduce the error.
Can you please describe all the user steps you are going through to encounter the error?

Thank you
Eugen

**Comment by johnboc** [comment] 2019-09-10 15:41
Download material-dashboard-pro-laravel-v1.0.0.zip and install and build. Login and go to /profile and it generates the following error. The typos on referenced in my initial post.
![typo_error](https://user-images.githubusercontent.com/26877327/64628360-8d237100-d3f1-11e9-9640-f220556d8ab8.png)

I need more time to recreate the undefined variable: classPage error

**Comment by Ghitu** [comment] 2019-09-10 16:43
Hello again. Thank you for your support.
We fixed the issue and pushed the fix.
You can download the archive from Creative Tim website again.

Best
Alin

**Comment by johnboc** [comment] 2019-09-11 13:48
undefined variable: classPage error
My index.blade.php is
```
@extends('layouts.app', ['activePage' => 'exhibitions', 'menuParent' => 'laravel', 'titlePage' => __('Exhibitions')])

@section('content') 
 . . .
@endsection
```
If the route
`Route::resource('exhibition', 'ExhibitionController');`
is outside of 
`Route::group(['middleware' => 'auth'], function () { }`
I get the error. 
I don't get the error when it's within the group. I can't see why this blade needs the classPage variable set when it's not in the Route:group.

**Closed** 2019-09-18 17:51 UTC
