### ISSUE TITLE
Uncaught TypeError: $(...).bootstrapMaterialDesign is not a function

### ISSUE THREAD

**Issue by amikrop** [creativetimofficial/ct-material-dashboard-pro-laravel#34] opened 2021-03-23 14:18 UTC
A similar issue already exists, but it is closed (without being resolved, as far as I understand). The problem exists for me, any solutions please? I am trying to clear the js console of all errors, to get the file input picker to work (it currently doesn't).

**Comment by teamupdivision** [comment] 2021-03-26 13:52
Hi @amikrop,

Thank you for reporting this issue and for using Creative Tim products.

Could you please send a few more details to us? We were not able to reproduce the error. Also, if you can fill out the form with the details on Prerequisites, Expected Behavior, Current Behavior, Steps and Context, it will help a lot. 

All the best,
Updivision Team

**Comment by teamupdivision** [comment] 2021-04-19 14:21
Hi there @amikrop,

We would like to check if the issue was solved or if you can share a few more details on the steps followed. Please let us know if there is anything else we can help with and if you have any other issues.

Best,
Updivision Team

**Comment by amikrop** [comment] 2021-04-20 00:36
Hello,
It was resolved, thanks.

**Comment by teamupdivision** [comment] 2021-04-20 10:49
Hi @amikrop,

Thank you very much for your answer. We're glad this was solved. When you have a moment, could you please let us know what solved the issue and if there are any details we should take into consideration? Any details or suggestions for improvements will be highly appreciated. 

All the best,
UPDIVISION Team

**Comment by teamupdivision** [comment] 2021-04-28 11:11
Hi @amikrop,
 
We're glad the problem was solved. We will go ahead and close this ticket. If there is anything else that can be fixed or we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).

**Closed by teamupdivision** 2021-04-28 11:11 UTC
